### ISSUE TITLE
shapes[shape].altText() returns only Alt description, Not the Alt title.

### ISSUE THREAD

**Issue by manoj-compro** [Miramac/node-office-script#13]
![alttext](https://cloud.githubusercontent.com/assets/22838010/19968172/72ad7d48-a1f9-11e6-8656-c77d84cfb803.png)
Is there any function to get the alt Title of an shape.
Please support this if not present.

**Comment by Miramac** [comment]
Sorry, not supported yet. I still work with office 2007 - there is no Alt Title ;-)
