### ISSUE TITLE
activeSlide() only works if the presentation is not in the slide show mode?

### ISSUE THREAD

**Issue by Lugo239** [Miramac/node-office-script#15]
Hey,

do smb know about the mentioned above issue? Iam able to get the active slide, but when iam in the slide show mode it does not work.

Thanks for your help!
Lugo

**Comment by Miramac** [comment]
Hi Lugo,
I will look at this in 2 weeks, right now I'm travelling.

**Comment by Miramac** [comment]
I changed the behavor of activeSlide().
If the presentation mode is active, you will the current slide of the slide show.
