### ISSUE TITLE
update dependencies for Node 8.x

### ISSUE THREAD

**Issue by adnan-kamili** [Miramac/node-office-script#16]
Hi,

Can you please update the edge version to 8.2.1 so that it can be used with node v8.x

**Comment by Miramac** [comment]
Hi @adnan-kamili,

I change the dependency from edge to the fork [edge-js](https://github.com/agracio/edge-js). I think this one is better maintained.

I tested it with node v8.9.4 and it worked well. The new version 1.4.0 is publish on npm.
