### ISSUE TITLE
Unhandled Exception: System.MissingMethodException

### ISSUE THREAD

**Issue by pratikgchaudhari** [Miramac/node-office-script#18]
Hi,
This is my code:

```
msOfficeIsInstalled.js:
-----------------------------------------------------------
const officeScript = require('office-script');
const Presentation = officeScript.Presentation;
let presentation = null;

module.exports = function (testFilePath) {

    try {
        presentation = new Presentation(testFilePath);
    } catch (err) {
        return false;
    }

    if (presentation) {
        presentation.quit();
    }
    return true;
}

app.js
-----------------------------------------------------------
const path = require('path');
const msOfficeIsInstalled = require('./msOfficeIsInstalled.js');

if (msOfficeIsInstalled(path.join(__dirname,'test.pptx'))) {
    console.log('MS Office is installed!');
} else {
    console.log('MS Office is not installed!');
}
```

When I do `node app.js`, I get the following error in console:

Unhandled Exception: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task System.Threading.Tasks
ueWith(System.Action`2<System.Threading.Tasks.Task`1<!0>,System.Object>, System.Object)'.
   at ClrFunc.Call(Local<v8::Value>* , Local<v8::Value> payload, Local<v8::Value> callback)
   at clrFuncProxy(FunctionCallbackInfo<v8::Value>* info)
   at Nan.imp.?A0x0f64e585.FunctionCallbackWrapper(FunctionCallbackInfo<v8::Value>* info)

My system's configuration:
---------------------------------------
**OS**: Windows 7, 32-bit
**node**: v8.9.4
**npm**: 5.6.0

**Comment by Miramac** [comment]
I've never seen this error before...

My first guess: Is .NET Framework v4.5 or higher installed?

**Comment by pratikgchaudhari** [comment]
Thanks!
