### ISSUE TITLE
Speaker Notes per slide?

### ISSUE THREAD

**Issue by cliqer** [Miramac/node-office-script#25]
Hi and thank you for this.
Is there a way to read and return PPT Speaker notes per slide?
If so what would be the best approach?

**Comment by Miramac** [comment]
Is unfortunately not yet possible. But I like the idea and believe it is a useful enhancement.

**Comment by Miramac** [comment]
try this:
````javascript
const path = require('path')
const Presentation = require('office-script').Presentation
const presentation = new Presentation(path.join(__dirname, 'myPresentation.pptx'))
// get all slides 
const slides = presentation.slides()
// get the notes of slide 2
const slideNotes = slides[1].notes()
console.log(slideNotes)
// close file and powerpoint
presentation.quit()
````

but the slide notes funtion is at the moment read only. Writing notes will be added later.

**Comment by cliqer** [comment]
Amazing! thank you
